# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-02 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200202_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Category'),
        ),
    ]
