# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-03 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20200203_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
